### ISSUE TITLE
Add CONTRIBUTING file so people can start contributing

### ISSUE THREAD

**Issue by yannbf** [yannbf/bit-wallet-manager#2]

**Comment by gdsrosa** [comment]
Have any contributing model?

**Comment by yannbf** [comment]
Yes! You can refer to [this](https://github.com/ifactory-solutions/inside-client/blob/master/CONTRIBUTING.md) as your guide. There's also the need of adding a code of conduct file, which I'm gonna open a new issue for that in a sec!

Thanks a lot for your interest, @gdsrosa :1st_place_medal:

**Comment by gdsrosa** [comment]
Okay, ready to go!!! Haha

**Comment by yannbf** [comment]
@gdsrosa There was a PR that added the code of conduct, so you can  just create the contributing file linking to the [already existing file](https://github.com/yannbf/bit-wallet-manager/blob/master/CODE_OF_CONDUCT.md) in this repo :)

**Comment by gdsrosa** [comment]
Yeah, I saw, no problem haha

**Comment by gdsrosa** [comment]
PR made!
