### ISSUE TITLE
Add TSLINT rules

### ISSUE THREAD

**Issue by yannbf** [yannbf/bit-wallet-manager#4]
Ionic projects have tslint integrated but don't have sets of rules apart from very basic standard ones. Ideally we should come up with good practices and tslint should be our guide.

**Comment by paulonotz0r** [comment]
Let me take this! :)

**Comment by yannbf** [comment]
Go for it! :D

Em 17 de out de 2017 10:26 AM, "Paulo Gabriel" <notifications@github.com>
escreveu:
